# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTeste():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_teste(self):
    self.driver.get("https://prex.env.sti.ufc.br/sigaa/verTelaLogin.do")
    self.driver.set_window_size(1550, 830)
    self.driver.find_element(By.NAME, "user.login").send_keys(Keys.DOWN)
    self.driver.find_element(By.NAME, "user.login").send_keys(Keys.TAB)
    self.driver.find_element(By.NAME, "user.senha").send_keys("a")
    self.driver.find_element(By.NAME, "user.senha").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) .col-xs-6").click()
    self.driver.find_element(By.CSS_SELECTOR, ".docente .texto").click()
    self.driver.find_element(By.CSS_SELECTOR, "#cmAction-105 > .ThemeOfficeMenuItemText").click()
    self.driver.find_element(By.CSS_SELECTOR, "#form\\3Aselecionar_autorizacao_ > img").click()
    self.driver.execute_script("window.scrollTo(0,422.3999938964844)")
    self.driver.find_element(By.ID, "form:autorizadoDpto").click()
    self.driver.find_element(By.CSS_SELECTOR, "#form\\3A autorizadoDpto > option:nth-child(2)").click()
    self.driver.find_element(By.ID, "form:tipo_autorizacao").click()
    dropdown = self.driver.find_element(By.ID, "form:tipo_autorizacao")
    dropdown.find_element(By.XPATH, "//option[. = 'AD-REFERENDUM']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#form\\3Atipo_autorizacao > option:nth-child(2)").click()
    self.driver.find_element(By.ID, "form:data_reuniao").click()
    self.driver.find_element(By.ID, "form:data_reuniao").send_keys("30/09/2023")
    self.driver.find_element(By.ID, "form:confirmar").click()
  
